# Database Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javapro_task7
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl: validate

# Server Configuration
server:
  port: 8080

# Remote Service Configuration
service-url:
  product:
    base-url: http://localhost:8081
    get-by-user: /product/{user_id}/get-by-user
    get-by-id: /product/{id}/get
    update: /product/update
